name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby (for bundler or CocoaPods if needed)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install Dependencies
      run: |
        brew install swiftlint
        xcodebuild -version
        xcode-select -p

    - name: SwiftLint
      run: |
        swiftlint

    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme MarvelXplorer \
          -workspace MarvelXplorer.xcodeproj \ # use .xcodeproj if not using workspace
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
